name: Docker Lint

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  hadolint:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Hadolint
        uses: burdzwastaken/hadolint-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
          HADOLINT_ACTION_DOCKERFILE_FOLDER: .
